<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Energía Consciente</title>
    <style>
        /* Hacer que el iframe ocupe toda la pantalla */
        html, body {
            margin: 0;
            padding: 0;
            height: 100%;
            overflow: hidden;
        }

        iframe {
            width: 100%;
            height: 100%;
            border: 0;
        }
    </style>
</head>
<body>
    <iframe id="JotFormIFrame-243119035728658" 
            title="EnergíaConsciente" 
            allow="geolocation; microphone; camera" 
            src="https://www.jotform.com/app/243119035728658?appEmbedded=1">
    </iframe>
</body>
</html>
